#!/usr/bin/python3
import sys



def read_data(name):
    with open(name) as f:
        contents = f.read()
        contents_ints = [int(x) for x in contents.split()]
        return contents_ints

def prime_num_generator():
    primeN = []
    for num in range(2, 100):
        if num > 1:
            for i in range(2, num):
                if (num % i) == 0:
                    break
            else:
                primeN.append(num)
    return primeN



def mul(a, b):
    for i in range(len(a)):
        for j in range(len(b)):
            if a[i] % b[j] == 0:
                x = a[i] // b[j]
                print("{}={}*{}".format(a[i], x, b[j]))
                break

data = read_data(sys.argv[1])
maximmum = max(data)
minimum = min(data)
primeNumbers = prime_num_generator()
mul(data, primeNumbers)