#!/usr/bin/python3
import math
import sys


def read_data(name):
    with open(name) as f:
        contents = f.read()
        contents_ints = [int(x) for x in contents.split()]
        return contents_ints

def max_prime_number(a):
    max_prime = 0
    """converting the number to odd"""
    while a % 2 == 0:
        max_prime = 2
        a = a / 2
    """ prime factors and replacing maxPrimeFactor"""
    for i in range(3, int(math.sqrt(a)) + 1, 2):
        while a % i == 0:
            max_prime = i
            a = a / i
    if a > 2:
        max_prime = a

    return int(max_prime)

def mul(num, prime_factor):
    x = num // prime_factor
    print("{}={}*{}".format(num, prime_factor, x))

data = read_data(sys.argv[1])
max_p_num = max_prime_number(data[0])

mul(data[0], max_p_num)
